config/routes.rb
Studio::Application.routes.draw do

  mount_opro_oauth
  devise_for :users, :controllers => {:sessions => "sessions"} 
  devise_scope :user do

    authenticated :user, lambda { |user| user.loginable_type == "Admin" } do
      root to: "customers#index"
    end

    authenticated :user, lambda { |user| user.loginable_type == "Teacher" } do
      root to: "teachers#personal", as: :teacher_root
    end

    unauthenticated :user do
      root :to => 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources   :users

  get '/daily', to: 'calendars#daily'
  
  get 'update_teachers', to: 'shared#update_teachers'
  
  get "lessons/teacher_booking"
  
  resources :lessons do
    get "sub_request", to: "attendances#sub_request"
    resources :attendances
  end
  
  get "extras/teacher_booking"
  
  resources :extras do
    resources :attendances
  end
  
  get "attendances/dialog"

  resources :instruments

  resources :rooms

  resources :teachers do
    devise_for :users, :controllers => {:registrations => "registrations"} 
    get 'weekly', to: 'calendars#weekly'
    get '/daily', to: 'calendars#daily'
  end
  
  get 'teachers_cbx', to: 'sharings#teachers_cbx'
  
  get 'teacher', to: 'teachers#personal'
  
  get 'sharing_search', to: 'detailed_sharings#sharing_search'
  
  match "update_attendance", to: "detailed_sharings#update_attendance", :via => :put
  
  resources :sharings do
    get "attendance", to: "detailed_sharings#attendance"
  end

  get 'attendance_search', to: 'students#attendance_search'
  
  resources :students do
    get 'attendance', to: 'students#attendance'
    resources :lessons
    resources :extras
    resources :detailed_sharings
  end
  
  get "customers/live_search"
  
  resources :customers do
    resources :students
    resources :telephones
    resources :addresses do
      resources :preffered_addresses
    end
    
  
  end

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id          :integer          not null, primary key
#  first       :string(255)
#  last        :string(255)
#  cell        :string(255)
#  email       :string(255)
#  birthdate   :date
#  grade       :integer
#  schoolyear  :date
#  customer_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Student < ActiveRecord::Base
 
  include FieldSanitizer
  
  belongs_to :customer
  
	has_many :telephones, :as => :phoneable, :dependent => :destroy
	accepts_nested_attributes_for :telephones, :allow_destroy => true, :reject_if => proc { |a| a['number'].blank? }
  
  has_many :lessons
  has_many :extras
  has_many :detailed_sharings
  
  attr_accessible :first, :last, :telephones_attributes, :email, :birthdate, :grade, :customer_id, :schoolyear
  
  before_validation { |student| student.nameize :first, :last }
  before_validation { |student| (student.email = student.email.strip.downcase) unless student.email.nil? }
  
	validates :first, presence: {message: "Enter first name"}, length: { maximum: 30 } 
	validates :last, presence: {message: "Enter last name"}, length: { maximum: 30 }
	
	validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, message: "Enter a valid email or leave blank" }, if: :email_present?
  
  def email_present?
    self.email.present?
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  allow_oauth! :except => :delete
  
  def index
    @students = Student.order("last ASC")
    respond_to do |format|
      format.html
      format.json { render :json => @students }
    end
      
  end

  def new
    @customer = Customer.find(params[:customer_id])
    @student = Student.new
    @student.telephones.build
  end

  def create
    @customer = Customer.find(params[:customer_id])
    #@student = @customer.students.build(params[:student])
    @student = @customer.students.build(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_path(@student), 
        notice: 'Student was successfully created.' }
      else
      format.html { render action: "new" }
        if @student.telephones.empty? 
          @student.telephones.build
        end
      end
    end
  end

  def edit
    @student = Student.find(params[:id])
    if @student.telephones.empty? 
      @student.telephones.build
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :action => 'edit'
      if @student.telephones.empty? 
        @student.telephones.build
      end
    end
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to customer_students_url }
      format.json { head :no_content }
    end
  end
  
  def show
    @student = Student.find(params[:id])
    @id = @student.id
    @lessons = @student.lessons.where("(end_date > ? OR end_date IS NULL)",Time.now).order("weekday ASC, start_time ASC")
    @extras =  @student.extras.where("date >= ?", Time.now.to_date).order("date ASC")
    @sharings = Sharing.where("date >= ? AND date <= ?", Time.now.beginning_of_month, Time.now.end_of_month)
    @upcoming_sharings = Sharing.where("date >= ?", Time.now)
    @date = Time.now.to_date.beginning_of_month
    @detailed_sharing  = Array.new
    @sharing_signup = Array.new
    @upcoming_detailed_sharings = Array.new
    for sharing in @sharings
      @sharing = DetailedSharing.where("sharing_id = ? AND student_id = ?", sharing.id, @student.id).first
      @detailed_sharing.push(@sharing) unless @sharing.nil?     
    end
    
    for sharing in @upcoming_sharings
      @sharing = DetailedSharing.where("sharing_id = ? AND student_id = ?", sharing.id, @student.id).first
      @upcoming_detailed_sharings.push(@sharing) unless @sharing.nil?     
    end
    
      @json_student = @student.attributes
      @customer = Customer.find(@student.customer_id)
      @json_student["customer"] = @customer.attributes
      @json_student["customer"]["telephones"] = @customer.telephones
      @mailing_address = @customer.preferred_addresses.where("description = 'mailing'")
      if @mailing_address.any?
       @mailing_address_id = @mailing_address.first.id
        @json_student["customer"]["mailing_address"] = Address.find(@mailing_address_id)
      end
    
    respond_to do |format|
      format.html
      format.json { render :json => @json_student }
    end
  end
  
  def attendance
    @student = Student.find(params[:student_id])
    @id = @student.id
    @lessons = @student.lessons.order("weekday ASC, start_time ASC")
    @extras =  @student.extras.where("date >= ?", Time.now.to_date).order("date ASC")
    @sharings = Sharing.where("date >= ? AND date <= ?", Time.now.beginning_of_month, Time.now.end_of_month)
    @upcoming_sharings = Sharing.where("date >= ?", Time.now)
    @date = Time.now.to_date.beginning_of_month
    @detailed_sharing  = Array.new
    @sharing_signup = Array.new
    @upcoming_detailed_sharings = Array.new
    for sharing in @sharings
      @sharing = DetailedSharing.where("sharing_id = ? AND student_id = ?", sharing.id, @student.id).first
      @detailed_sharing.push(@sharing) unless @sharing.nil?     
    end
    if @detailed_sharing.any?
      for detailed_sharing in @detailed_sharing
       @sharing = Sharing.find(detailed_sharing.sharing_id)
       @sharing_signup.push(@sharing)
      end
    end
  end
  
  def attendance_search
    @student = Student.find(params[:id])
    @lessons = @student.lessons
    render :layout => false
  end
  
  private
  
  def student_params
  params.require(:student).permit(:first, :last, :email, :birthdate, :grade, :customer_id, :schoolyear, telephones_attributes: [ :id, :_destroy, :number, :description ]) 
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  
  def school_grades
      [
        ['Kinder', 0],
        ['1st', 1],
        ['2nd', 2],
        ['3rd', 3],
        ['4th', 4],
        ['5th', 5],
        ['6th', 6],
        ['7th', 7],
        ['8th', 8],
        ['9th', 9],
        ['10th', 10],
        ['11th', 11],
        ['12th', 12]
      ]
  end
  
  def grade_display
    a = school_grades
    b = Array.new
    a.each do |key, value|
      b.push(key)
    end
    return b
  end
  
  def current_grade(year, grade)
    a = Time.now.year - year
    Time.now.month < 8 ? b = 1: b = 0
    @current_grade = grade + a - b
    return @current_grade
  end
  
  def month_lessons(lesson, date)
  	@lesson_weekday = lesson.weekday
  	@month_first_wday = date.wday
  	@days_apart = @lesson_weekday - @month_first_wday
  	@first_lesson_of_month = date + @days_apart
  	@lesson_date = @first_lesson_of_month
  	while @lesson_date < date or @lesson_date < lesson.start_date do
  		@lesson_date += 7
  	end
    
    @sharings = Sharing.where("date >= ? AND date <= ?", date, date.end_of_month).order("date ASC")
    @sharings_dates = Array.new
    @sharings.each do |sharing|
      @sharings_dates.push(sharing.date)
    end
	
  	@month_lessons = Array.new
  	while @lesson_date <= @date.end_of_month do
     unless @sharings_dates.include?(@lesson_date)
  		  @attendance = Attendance.new
        @attendance.teacher_id = lesson.teacher_id
        @attendance.date = @lesson_date
        @attendance.status = "s"
  		  @month_lessons.push(@attendance)
     end
     @lesson_date += 7
  	end
    
  	@attendances = lesson.attendances.where("date >= ? AND date <= ?", date, date.end_of_month).order("date ASC")
  	@attendances.each do |attendance|
  		@attendance_index = @month_lessons.find_index{|n| n['date'] == attendance.date }
          if @attendance_index
        		@lesson_time = join_date_time(attendance.date, lesson.end_time)
        		if @lesson_time < Time.now
        		  if attendance.status == "s" 
        		    attendance.status = "u"
              end
        		end
            @month_lessons[@attendance_index] = attendance
          end
  	end
    
    return @month_lessons
  end
  
end

app/views/students/_form.html.erb
<div class="form-container">
<%= form_for [@customer, @student] do |f| %>
  
<%= render "layouts/basic_info_form", :f => f, :@person => @student %>

<div>
	<%= f.fields_for :telephones do |builder| %>
  	<%= render "telephones/telephone_fields", :f => builder, :@person => @student %>
	<% end %>
</div>
<div class="field">
 <%= link_to_add_fields '<i class="icon-plus icon-white"></i>'.html_safe, f, :telephones, class: "btn btn-success tooltip_right" %>
</div> 

<div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate, {:order => [:month, :day, :year], :start_year => 1950, :use_short_month => true, :prompt => [:day => 'Select day', :month => 'Select month', :year => 'Select year']}, {:class => "input-sm"} %>
</div>

<div class="field inline">
    <%= f.label :grade %>
    <%= f.select :grade, school_grades, {include_blank: 'Select'}, :class => "input-med" %>
</div>

<div class="field inline">
    <%= f.label :schoolyear, "as of &nbsp;".html_safe, :class => "inline" %>
    <%= f.date_select :schoolyear, {:order => [:year], :start_year => 2010, :prompt => [:year => 'Select year']}, {:class => "input-sm"} %>
</div>
  
<div class = "actions">
	<%= f.submit submit_button_message(yield(:button_message)), class: "btn btn-large btn-primary" %>
</div>
<% end %>
</div>

app/views/students/attendance.html.erb
<h1>Attendance for</h1>
<h3><%= "#{@student.first} #{@student.last}" %></h3>
</p>
<%= select_date Date.current, {:order => [:year, :month], :use_short_month => true, :end_year => Time.now.year + 2}, {:class => "input-sm date-search"} %>


<input type="hidden" id="hidden_field" value='<%= "#{@student.id}" %>' />
<div id="attendance_result">
	<%= render file: "/students/attendance_search" %>
</div></br>
<%= link_to 'Back to Student Info', student_path(@student) %>

app/views/students/attendance_search.html.erb
<% if params[:year] and params[:month] and params[:id]%>
	<% @date = Date.new(y=params[:year].to_i, m=params[:month].to_i) %>
<% end %>
<% @extra_attendances = @student.extras.where("date >= ? AND date <= ?", @date, @date.end_of_month).order("date ASC") %>

<% @sharings = Sharing.where("date >= ? AND date <= ?", @date, @date.end_of_month).order("date ASC") %>
<% @detailed_sharing  = Array.new %>
<% @sharing_signup = Array.new %>
<% for sharing in @sharings %>
  <% @sharing = DetailedSharing.where("sharing_id = ? AND student_id = ?", sharing.id, @student.id).first %>
  <% @detailed_sharing.push(@sharing) unless @sharing.nil? %>    
<% end %>
<% if @detailed_sharing.any? %>
  <% for detailed_sharing in @detailed_sharing %>
   <% @sharing = Sharing.find(detailed_sharing.sharing_id) %>
   <% @sharing_signup.push(@sharing) %>
  <% end %>
<% end %>

<h4>Regular Lessons:</h4>
<% @lessons.each do |lesson| %>
<% @month_lessons = month_lessons(lesson, @date)%>
<% if @month_lessons.any? %>
<p><b><%= Instrument.find(lesson.instrument_id).name %></b></p>
<table class="table table-hover">
	<thead>
		<tr>
			<th class="span3">Date</th>
			<th class="span3">Time</th>
			<th class="span2">Status</th>
			<th class="span2">Teacher</th>
			<th></th>
		</tr>
	</thead>	
	
	
	<% @month_lessons.each do |attendance| %>
		<% @status = status_name(attendance.status, "web") %>
		<% @day = format_day(attendance.date) %>
		<% @start = format_time(lesson.start_time) %>
		<% @end = format_time(lesson.end_time) %>
		<% if attendance.teacher_id == "" or attendance.teacher_id.nil? %>
			<% @teacher = "Need Sub" %>
		<% else %>
			<% @teacher = Teacher.find(attendance.teacher_id).first %>
		<%end%>
		<tr>
			<td><%= link_to "#{@day}", daily_path(date: attendance.date.to_time.to_i), method: "get" %></td>
			<td><%= "#{@start} - #{@end}" %></td>
			<td><%= @status %></td>
			<td><%= @teacher %></td>
			<td><%= link_to 'Get Sub', lesson_sub_request_path(lesson, {date: attendance.date}), class: "btn btn-mini btn-primary" %></td>
		</tr>
	<% end %> 
</table>
<% end %>
<% end %>

<% if @extra_attendances.any? %>
<h4>Make Ups And Extra Lessons:</h4>
<table class="table table-hover">
	<thead>
		<tr>
			<th class="span3">Date</th>
			<th class="span3">Time</th>
			<th class="span2">Status</th>
			<th class="span2">Teacher</th>
			<th></th>
		</tr>
	</thead>	
	<% for extra in @extra_attendances %>
		<% @day = format_day(extra.date) %>
		<% @start = format_time(extra.start_time) %>
		<% @end = format_time(extra.end_time) %>
		<% @teacher = Teacher.find(extra.teacher_id) %>
		<% @lesson_time = join_date_time(extra.date, extra.end_time) %>
		<% if @lesson_time < Time.now and extra.attendances.first.status == "s" %>
			<%@status = status_name("u", "web") %>
		<% else %>
			<% @status = status_name(extra.attendances.first.status, "web") %>
		<% end %>
		
<tr>
	<td><%= link_to "#{@day}", daily_path(date: extra.date.to_time.to_i), method: "get" %></td>
	<td><%= "#{@start} - #{@end}" %></td>
	<td><%= @status %></td>
	<td><%= @teacher.first %></td>
	<td><%= link_to "Edit", edit_student_extra_path(@student, extra), class: "btn btn-mini btn-primary" %></td>
</tr>
	<% end %>
</table>
<% end %>

<% if @sharing_signup.any?%>
<h4>Sharing:</h4>
<table class="table table-hover">
	<thead>
		<tr>
			<th class="span3">Date</th>
			<th class="span3">Time</th>
			<th class="span2">Status</th>
			<th></th>
		</tr>
	</thead>	

		<% for sharing in @sharing_signup %>
		<% @detailed_sharing = @student.detailed_sharings.where("sharing_id = ?", sharing.id).first %>
		<td><%= link_to "#{format_day(sharing.date)}", sharing_path(sharing) %></td>
		<td><%= "#{format_time(sharing.start_time)} - #{format_time(sharing.end_time)}"%></td>
		<% @time = join_date_time(sharing.date, sharing.start_time) %>
			<% if @time >= Time.now %>
				<td><span class = "text-info">Signed up</span></td>
			<% else %>
				<td><%= sharing_attendance(@detailed_sharing.attendance) %></td>
			<% end %>
			<% if @time >= Time.now %>
			<td><%= link_to 'Edit', edit_student_detailed_sharing_path(@student, @detailed_sharing ), class: "btn btn-mini btn-primary" %></td>
			<% end %>
		<% end %>
</table>
<% end %>

app/views/students/edit.html.erb
<% provide(:title, 'Update Student Info') %>
<% provide(:button_message, 'Update Student') %>


<%= render 'form' %>

app/views/students/index.html.erb
<% provide(:title, 'Students') %>
<table class="table table-hover">
  <tr>
    <th>Last</th>
    <th>First</th>
    <th>Cell</th>
    <th>Email</th>
    <th>Birthdate</th>
    <th class = "center">Grade</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% for student in @students %>
  <% @customer = Customer.find(student.customer_id) %>
  <% if student.schoolyear and student.grade %>
  	<% @grade = current_grade(student.schoolyear.year, student.grade) %>
  	<% @grade < 0 ? @current_grade = "Pre-school" : @current_grade = grade_display[@grade] %>
  <% else %>
  	<% @current_grade = "N/A" %>
  <% end %>
    <tr>
      <td><%= student.last %></td>
      <td><%= student.first %></td>
      <td><%= student.telephones.any? ? formated_phone(student.telephones.first.number) : "" %></td>
      <td><%= student.email %></td>
      <td><%= student.birthdate.strftime('%b %d, %Y') unless student.birthdate.nil? %></td>
      <td class = "center"><%= @current_grade %></td>
      <td><%= link_to "#{@customer.first.first}. #{@customer.last}", customer_path(@customer) %></td>
      <td><%= link_to 'Info', student %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Delete', student, method: :delete, remote: true, class: "triger" %></td>
      </tr>
    <% end %>
</table>
<%= render :partial => 'shared/alert' %>
      

app/views/students/new.html.erb
<% provide(:title, 'New Student') %>
<% provide(:button_message, 'Add Student') %>

<h1>New Student For</h1>
<h2><%= "#{@customer.first} #{@customer.last}" %></h2>
<%= render 'form' %>

<%= link_to 'Back', customer_students_path %>

app/views/students/show.html.erb
<b>Student:</b>
<p>
	<%= "#{@student.first} #{@student.last}" %>
</p>
<% if @student.email  %>
<p>
  <b>Email:</b>
  <%= @student.email %>
</p>
<% end %>
<% if @student.telephones.any? %>
<p>
	<b>Telephones:</b></br>
	<ul>
	<% for telephone in @student.telephones %>
		<li>
			<%= formated_phone(telephone.number) %>&nbsp;
			<%= telephone.description %>
		</li>
	<% end %>
<% end %>
	</ul>
</p>
<% if @lessons.any? %>
<p>
	<b>Regular Lessons:</b></br>
</p>
<table class="table table-hover">
	<thead>
		<tr>
			<th class = "span2">Instrument</th>
			<th class = "span3">Day</th>
			<th class = "span3">Time</th>
			<th class = "span2">Teacher</th>
			<th class = "span3"></th>
			<th></th>
		</tr>
	</thead>
	<% for lesson in @lessons %>
	<% @start = format_time(lesson.start_time) %>
	<% @end = format_time(lesson.end_time) %>
	<tr>
		<td>
			<%= Instrument.find(lesson.instrument_id).name %>
		</td>
		<td>
			<%= Date::DAYNAMES[lesson.weekday]%>
		</td>
		<td>
			<%= "#{@start} - #{@end}" %>
		</td>
		<td>
			<%= Teacher.find(lesson.teacher_id).first %>
		</td>
		<td></td>
		<td>
			<%= link_to 'Edit', edit_lesson_path(lesson), class: "btn btn-mini btn-info" %>
		</td>
	</tr>		
	<% end %>
</table>
<% end %>
<p>
	<b>Upcoming Make Up and Extra Lessons:</b></br>
</p>
<% if @extras.any? %>
<table class="table table-hover">
	<thead>
		<tr>
			<th class = "span2">Instrument</th>
			<th class = "span3">Date</th>
			<th class = "span3">Time</th>
			<th class = "span2">Teacher</th>
			<th class = "span3">Type</th>
			<th></th>
		</tr>
	</thead>
	<% for extra in @extras %>
	<% @start = format_time(extra.start_time) %>
	<% @end = format_time(extra.end_time) %>
	<tr>
		<td>
			<%= Instrument.find(extra.instrument_id).name %>
		</td>
		<td>
			<%= format_day(extra.date)%>
		</td>
		<td>
			<%= "#{@start} - #{@end}" %>
		</td>
		<td>
			<%= Teacher.find(extra.teacher_id).first %>
		</td>
		<td>
			<%= extra_category_description(extra.category) %>
		</td>
		<td>
			<%= link_to 'Edit', edit_student_extra_path(@student, extra), class: "btn btn-mini btn-info" %>
		</td>
		<td>
			<%= link_to '<i class="icon-minus icon-white"></i>'.html_safe, extra, method: :delete, remote: true, title: "Delete Lesson", class: "triger btn btn-mini btn-danger bold tooltip_right" %>
		</td>
	</tr>		
	<% end %>
</table>
<% else %>
<p>No make ups scheduled.</p></br>
<% end %>
<p>
	<b>Sharing Sign Up:</b></br>
</p>
<% %>
<% if @upcoming_detailed_sharings.any? %>
<table class="table table-hover">
	<thead>
		<tr>
			<th class = "span3">Date</th>
			<th class = "span3">Time</th>
			<th></th>
		</tr>
	</thead>

	<% for sharing in @upcoming_detailed_sharings %>
		<% @sharing = Sharing.find(sharing.sharing_id) %>
		<% @start = format_time(@sharing.start_time) %>
		<% @end = format_time(@sharing.end_time) %>
		<tr>
			<td>
				<%= link_to "#{format_day(@sharing.date)}", sharing_path(@sharing) %>
			</td> 
			<td>
				<%= "#{@start} - #{@end}" %>
			</td>
			<td>
				<%= link_to 'Change', edit_student_detailed_sharing_path(@student, sharing ), class: "btn btn-mini btn-info" %>
			</td>
		</tr>
	<% end %>
</table>
</br>
<% else %>
<p>This Student is not signed up for any upcoming sharings</p>
<% end %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Customer Info', customer_path(@student.customer) %> |
<%= link_to 'Add Lesson', new_student_lesson_path(@student) %> |
<%= link_to 'Add Make Up/Extra Lesson', new_student_extra_path(@student) %> |
<%= link_to 'Sign Up For Sharing', new_student_detailed_sharing_path(@student) %> |
<%= link_to 'Attendance', student_attendance_path(@student) %>

<%= render :partial => 'shared/alert' %>