config/routes.rb
Studio::Application.routes.draw do

  mount_opro_oauth
  devise_for :users, :controllers => {:sessions => "sessions"} 
  devise_scope :user do

    authenticated :user, lambda { |user| user.loginable_type == "Admin" } do
      root to: "customers#index"
    end

    authenticated :user, lambda { |user| user.loginable_type == "Teacher" } do
      root to: "teachers#personal", as: :teacher_root
    end

    unauthenticated :user do
      root :to => 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources   :users

  get '/daily', to: 'calendars#daily'
  
  get 'update_teachers', to: 'shared#update_teachers'
  
  get "lessons/teacher_booking"
  
  resources :lessons do
    get "sub_request", to: "attendances#sub_request"
    resources :attendances
  end
  
  get "extras/teacher_booking"
  
  resources :extras do
    resources :attendances
  end
  
  get "attendances/dialog"

  resources :instruments

  resources :rooms

  resources :teachers do
    devise_for :users, :controllers => {:registrations => "registrations"} 
    get 'weekly', to: 'calendars#weekly'
    get '/daily', to: 'calendars#daily'
  end
  
  get 'teachers_cbx', to: 'sharings#teachers_cbx'
  
  get 'teacher', to: 'teachers#personal'
  
  get 'sharing_search', to: 'detailed_sharings#sharing_search'
  
  match "update_attendance", to: "detailed_sharings#update_attendance", :via => :put
  
  resources :sharings do
    get "attendance", to: "detailed_sharings#attendance"
  end

  get 'attendance_search', to: 'students#attendance_search'
  
  resources :students do
    get 'attendance', to: 'students#attendance'
    resources :lessons
    resources :extras
    resources :detailed_sharings
  end
  
  get "customers/live_search"
  
  resources :customers do
    resources :students
    resources :telephones
    resources :addresses do
      resources :preffered_addresses
    end
    
  
  end

end

app/models/instrument.rb
# == Schema Information
#
# Table name: instruments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Instrument < ActiveRecord::Base
  include FieldSanitizer
  has_and_belongs_to_many :teachers
  has_many :lessons
  attr_accessible :name
  before_validation { |instrument| instrument.nameize :name }
end

app/models/sharing.rb
# == Schema Information
#
# Table name: sharings
#
#  id         :integer          not null, primary key
#  date       :date
#  start_time :time
#  end_time   :time
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sharing < ActiveRecord::Base
  
  has_and_belongs_to_many :students
  has_and_belongs_to_many :teachers
  has_many :detailed_sharings
  
  attr_accessor :status
  attr_accessor :comp_id
  attr_accessor :student_id
  attr_accessor :teacher_id
  attr_accessor :room_id
  
  accepts_nested_attributes_for :teachers
  accepts_nested_attributes_for :detailed_sharings
  
  attr_accessible :end_time, :date, :start_time, :teacher_ids
  
  #:comp_id, :status
end

app/controllers/sharings_controller.rb
class SharingsController < ApplicationController

  def index
    @sharings = Sharing.all
  end

  def show
    @sharing = Sharing.find(params[:id])
    @teachers = @sharing.teachers
    @detailed_sharings = DetailedSharing.where("sharing_id = ?", @sharing.id)
    @students = Array.new
    @detailed_sharings.each do |detailed_sharing|
      @students.push(Student.find(detailed_sharing.student_id))
      @students.sort_by!{ |m| [m.last, m.first] }
    end
    @attendance_total = @detailed_sharings.where("attendance = true").count
    @memory_total = @detailed_sharings.where("memory = true").count
    @practice_total = @detailed_sharings.where("practice = true").count
  end

  def new
    @sharing = Sharing.new
    @teachers = ""
    gon.start_time = "04:00 PM"
    gon.end_time = "05:00 PM"
  end

  def edit
    @sharing = Sharing.find(params[:id])
    @date = @sharing.date.strftime("%m/%d/%Y")
    gon.start_time = view_context.format_time(@sharing.start_time)
    gon.end_time = view_context.format_time(@sharing.end_time)
  end

  def create
    @sharing = Sharing.new(sharing_params)
    respond_to do |format|
      if @sharing.save
        format.html { redirect_to @sharing, notice: 'Sharing was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    params[:sharing][:teacher_ids] ||= []
    @sharing = Sharing.find(params[:id])

    respond_to do |format|
      if @sharing.update_attributes(sharing_params)
        format.html { redirect_to @sharing, notice: 'Sharing was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @sharing = Customer.find(params[:id])
    @sharing.destroy

    respond_to do |format|
      #format.html { redirect_to sharings_url }
      format.js
    end
  end
  
  
  def teachers_cbx
    @lessons = Lesson.where("weekday = ?", params[:weekday].to_i)
    @teachers = Array.new
    for lesson in @lessons
      @teachers.push(lesson.teacher_id)
    end 
    
    render :layout => false
  end
  
  def attendance
    @sharing = Sharing.find(params[:sharing_id])
    @detailed_sharings = @sharing.detailed_sharings
    @students = Array.new
    @detailed_sharings.each do |detailed_sharing|
      @students.push(Student.find(detailed_sharing.student_id))
      @students.sort_by!{ |m| [m.last, m.first] }
    end
  end
  
  def update_attendance
    @sharing = Sharing.find(params[:sharing_id])
    #params['detailed_sharing'].keys.each do |id|
      #@detailed_sharing = DetailedSharing.find(id.to_i)
      #@detailed_sharing.update_attributes(sharing_params)
      @sharing.update_attributes(update_params)
      #end
    respond_to do |format|
      
      format.js
    end
  end
  
  private
  
  def sharing_params
  params.require(:sharing).permit(:end_time, :date, :start_time, teacher_ids: []) 
  end
  
end

app/views/sharings/_form.html.erb
<div class="form-container">
<%= form_for(@sharing) do |f| %>
  <% if @sharing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sharing.errors.count, "error") %> prohibited this sharing from being saved:</h2>

      <ul>
      <% @sharing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <fieldset>
	  <legend>Sharing Time Details</legend>
	  <br/>
  	  <div class="field">
    	  <%= label_tag :date %>
    	  <%= text_field_tag "date-box-sharing", @date %>
  	  </div>
  	  <div class="field">
    	  <%= f.hidden_field :date, :class => "db-date", :id => "sharing-date" %>
      </div>
  
  	  <div class="field input-append bootstrap-timepicker">
    	  <%= f.label :start_time %>
    	  <%= f.text_field :start_time, :id => "timepicker_start", :class => "input-sm timepicker" %>
		  <span class="add-on"><i class="icon-time"></i></span>
  	  </div>
  	  <div class="field input-append bootstrap-timepicker">
    	  <%= f.label :end_time %>
    	  <%= f.text_field :end_time, :id => "timepicker_end", :class => "timepicker input-sm" %>
		  <span class="add-on"><i class="icon-time"></i></span>
  	  </div>
  </fieldset>
  <div id = "teacher_check_box">
  <% for teacher in Teacher.find(:all) %>  
      <div>  
        <%= check_box_tag "sharing[teacher_ids][]", teacher.id, @sharing.teachers.include?(teacher), :class => 'checkbox' %>  
        <%= teacher.first %>  
      </div>  
  <% end %>
	</br>
  </div>  
		
  <div class="actions">
    <%= f.submit submit_button_message(yield(:button_message)), class: "btn btn-large btn-primary" %>
  </div>
<% end %>
</div>

app/views/sharings/edit.html.erb
<% provide(:title, 'Update Sharing') %>
<% provide(:button_message, 'Update Sharing') %>

<h1>Editing sharing</h1>

<%= render 'form' %>

<%= link_to 'Show', @sharing %> |
<%= link_to 'Back', sharings_path %>

app/views/sharings/index.html.erb
<% provide(:title, 'Sharings') %>
<table class="table table-hover">
  <tr>
    <th>Date</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sharings.each do |sharing| %>
  <tr>
    <td><%= format_day(sharing.date) %></td>
    <td><%= format_time(sharing.start_time) %></td>
    <td><%= format_time(sharing.end_time) %></td>
    <td><%= link_to 'Show', sharing %></td>
    <td><%= link_to 'Edit', edit_sharing_path(sharing) %></td>
    <td><%= link_to 'Destroy', sharing, method: :delete, remote: true, class: "triger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sharing', new_sharing_path, class: "btn btn-small btn-primary" %>
<%= render :partial => 'shared/alert' %>

app/views/sharings/new.html.erb
<% provide(:button_message, 'Add Sharing') %>
<h1>New sharing</h1>

<%= render 'form' %>

<%= link_to 'Back', sharings_path %>

app/views/sharings/show.html.erb
<% provide(:title, 'Sharings') %>
<p id="notice"><%= notice %></p>

<h1>Sharing summary</h1>

<p>
  <b>Date:</b>
  <%= format_day @sharing.date %>
</p>

<p>
  <b>Start time:</b>
  <%= format_time @sharing.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= format_time @sharing.end_time %>
   
   <h4>Teachers:</h4>
<p>
	<ul>
     <% for teacher in @teachers %> 
	 	<li>
 			<%= link_to "#{teacher.first}", teacher_path(teacher) %>
		</li>
	<% end %>
	</ul>
</p>

   <h4>Students:</h4>
<table class="table table-hover">
	<thead>
		<tr>
			<th>Name</th>
			<th class = "center">Attendance</th>
			<th class = "center">Memory</th>
			<th class = "center">Practice</th>
		</tr>
	</thead>
	<tr>
     <% for student in @students %>
	 	<% @student = DetailedSharing.where("student_id = ? AND sharing_id = ?", student.id, @sharing.id).first %>
	 	<td>
 			<%= link_to "#{student.last} #{student.first}", student_path(student) %>
		</td>
		<td class = "center">
			<%= sharing_attendance(@student.attendance) %>
		</td>
		<td class = "center">
			<%= @student.memory == true ? "X" : "" %>
		</td>
		<td class = "center">
			<%= @student.practice == true ? "X" : "" %>
		</td>
	</tr>
	<% end %>
	<tr>
		<td>
			<b>Total</b>
		</td>
		<td class = "center">
			<%= @attendance_total %>
		</td>
		<td class = "center">
			<%= @memory_total %>
		</td>
		<td class = "center">
			<%= @practice_total %>
		</td>
	</tr>
</table>


<%= link_to 'Edit', edit_sharing_path(@sharing) %> |
<%= link_to 'Back', sharings_path %> |
<%= link_to 'Sharing Attendance', sharing_attendance_path(@sharing) %>

app/views/sharings/teachers_cbx.html.erb
<div id = "teacher_check_box">
    <% for teacher in Teacher.find(:all) %>  
        <div> 

          <%= check_box_tag "sharing[teacher_ids][]", teacher.id, @teachers.include?(teacher.id), :class => 'checkbox' %>  
          <%= teacher.first %>  
        </div>  
    <% end %>
	</br> 
</div>