config/routes.rb
Studio::Application.routes.draw do

  mount_opro_oauth
  devise_for :users, :controllers => {:sessions => "sessions"} 
  devise_scope :user do

    authenticated :user, lambda { |user| user.loginable_type == "Admin" } do
      root to: "customers#index"
    end

    authenticated :user, lambda { |user| user.loginable_type == "Teacher" } do
      root to: "teachers#personal", as: :teacher_root
    end

    unauthenticated :user do
      root :to => 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources   :users

  get '/daily', to: 'calendars#daily'
  
  get 'update_teachers', to: 'shared#update_teachers'
  
  get "lessons/teacher_booking"
  
  resources :lessons do
    get "sub_request", to: "attendances#sub_request"
    resources :attendances
  end
  
  get "extras/teacher_booking"
  
  resources :extras do
    resources :attendances
  end
  
  get "attendances/dialog"

  resources :instruments

  resources :rooms

  resources :teachers do
    devise_for :users, :controllers => {:registrations => "registrations"} 
    get 'weekly', to: 'calendars#weekly'
    get '/daily', to: 'calendars#daily'
  end
  
  get 'teachers_cbx', to: 'sharings#teachers_cbx'
  
  get 'teacher', to: 'teachers#personal'
  
  get 'sharing_search', to: 'detailed_sharings#sharing_search'
  
  match "update_attendance", to: "detailed_sharings#update_attendance", :via => :put
  
  resources :sharings do
    get "attendance", to: "detailed_sharings#attendance"
  end

  get 'attendance_search', to: 'students#attendance_search'
  
  resources :students do
    get 'attendance', to: 'students#attendance'
    resources :lessons
    resources :extras
    resources :detailed_sharings
  end
  
  get "customers/live_search"
  
  resources :customers do
    resources :students
    resources :telephones
    resources :addresses do
      resources :preffered_addresses
    end
    
  
  end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
  
  def prerender_calendar(lessons, rooms, num_rooms, num_rows, first_slot_time)
    
#  @columns is an array of lessons for each room for the selected day.
    
    @columns = Array.new
    rooms.each do |room|
      @columns[room.id] = Array.new
    end

    if lessons
      lessons.each do |lesson|
        @start_time = lesson.start_time
        @end_time = lesson.end_time
        @room = lesson.room_id
        @lesson_length = (@end_time - @start_time)/60/15
        @slot_number = (@start_time - first_slot_time)/60/15
        lesson.status.nil? ? @status = "s" : @status = lesson.status
        lesson.student_id.nil? ? @student = "" : @student = "#{lesson.student.first.first}. #{lesson.student.last}"
        
        if lesson.status == "sh"
          @teacher = "SHARING"
        else
        lesson.teacher_id.nil? ? @teacher = "Need Sub" : @teacher = lesson.teacher.first
        end
      
      
        @columns[@room].push({ 
          :id => lesson.comp_id, 
          :room => @room, 
          :teacher => @teacher,
          :student => @student, 
          :start_time => @start_time, 
          :end_time => @end_time, 
          :slot => @slot_number,  
          :length => @lesson_length,
          :status => @status }) #  default is (s = scheduled)
      end
    end
    
#  @slot contains an array of lessons for each slot.
    
    @slot = Array.new
    rooms.each do |room|
      @slot[room.id] = Array.new(num_rows){Array.new}
    end
    
    if @columns
      @columns.each do |column|
        if column != nil
          i = 0
          while i < column.count do
            t = 0
            while t < column[i][:length] do
              @number = column[i][:slot] + t
              @room = column[i][:room]
              @slot[@room][@number].push(column[i][:id])
              t += 1
            end
            i += 1
          end
        end
      end
    end
    
#  @max_num is an array of max number of conflicts for each lesson for each room.

    @max_num = Array.new
    rooms.each do |room|
      @max_num[room.id] = Hash.new
    end
    
    d = 0
    while d < num_rooms
      if @columns[d] != nil
        @columns[d].each do |column|
          i = 0
          while i < column[:length]
            @slot_number = column[:slot]
            @keys = @slot[d][@slot_number].count
            @keys_next = @slot[d][@slot_number + i].count
            @lesson_id = column[:id]
            @max_num[d].merge!({@lesson_id => @keys})
            if @keys_next > @max_num[d][@lesson_id]
              t = 0
              while t < column[:length]
                @slot[d][@slot_number + t].each do |event|
                  @max_num[d][event] = @keys_next
                end
                t += 1
              end
            end
            i += 1
          end
        end
      end
      d += 1
    end
    
#  fine tune the graph and loops twice to correct problems   
    t = 0
    while t < 2 do
      d = 0
      while d < num_rooms do
        if @slot[d] != nil
          i = 0
          while i < num_rows do
            @max = 0
            if @slot[d][i] != nil
              @slot[d][i].each do |lesson_id|
                @new_max = @max_num[d][lesson_id]
                if @new_max > @max
                  @max = @new_max
                end
              end
              @slot[d][i].each do |lesson_id|
                @max_num[d][lesson_id] = @max
              end
            end
            i += 1
          end
        end
        d += 1
      end
      t += 1
    end
    
#  makes an array of index for each event. The index is the position in which 
#  an event is placed in the calendar from left to right.
   
    @index = Array.new
    @index_array = Array.new
    rooms.each do |room|
      @index_array[room.id] = Hash.new
    end
    d = 0
    while d < num_rooms do
      if @slot[d] != nil
        sl = 0
        while sl < num_rows do
          @keys = @slot[d][sl].count
          @prev = @slot[d][sl - 1]
          @index.clear
          if @prev
            i = 0
            while i < @keys do
              if @prev.include?(@slot[d][sl][i]) 
                @index.push(@index_array[d][@slot[d][sl][i]])
              else
                if @index.empty?
                  @counter = 0
                  @slot[d][sl].each do |event|
                    @index_array[d].merge!(event => @counter)
                    @counter += 1
                  end
                else
                  @index.sort! {|x,y| x <=> y }
                  @counter = 0
                  while @index[@counter] == @counter do
                    @counter += 1
                  end
                  @index_array[d][@slot[d][sl][i]] = @counter
                  @index.push(@counter) 
                end
              end
              i += 1
            end
          else
            @counter = 0
            if @slot[d][sl] != nil
              @slot[d][sl].each do |event|
                @index_array[d].merge!(event => @counter)
                @counter += 1
              end
            end
          end
          sl += 1
        end
      end
      d += 1
    end
    
#  makes an array with the ids and indexes of lessons per slot ordered by index
    
    @event_index = Array.new
    rooms.each do |room|
      @event_index[room.id] = Array.new(num_rows){Array.new}
    end
    
    d = 0
    while d < num_rooms do
      i = 0
      if @slot[d] != nil
        while i < num_rows do
          if @slot[d][i] != nil 
            @slot[d][i].each do |id|
              @event_index[d][i].push({:index=>@index_array[d][id], :id => id})
              @event_index[d][i].sort! {|a,b| a[:index] <=> b[:index]}
            end
          end
          i += 1
        end
      end
      d += 1
    end
    
# Calculates when an event needs more than 1 space.
    @num_slots = Hash.new
    d = 0
    while d < num_rows
      if @columns[d] != nil
        	@columns[d].each do |column|
        	@num_slots.merge!(column[:id] => @max_num[d][column[:id]] - @index_array[d][column[:id]])
        end
        sl = 0
        while sl < num_rows do
        	if @event_index[d][sl] != nil
        		@num_events = @event_index[d][sl].count
            i = 0
        		while i < (@num_events - 1) do
        			@ind = @event_index[d][sl][i][:index]
        			@next_ind = @event_index[d][sl][i+1][:index]
        			@event_id = @event_index[d][sl][i][:id]
        			@result = @next_ind - @ind
        			if @num_slots[@event_id] != nil
                if @num_slots[@event_id] > @result
        						@num_slots[@event_id] = @result
                end
              end
              i += 1
            end
          end
        sl += 1
        end
      end
      d += 1
    end
  end
    
    def prerender_weekly_calendar(lessons, num_columns, num_rows, first_slot_time)
    
  #  @columns is an array of lessons for each day.
    
      @columns = Array.new
      d = 0
      while d < num_columns do
        @columns[d] = Array.new
        d += 1
      end

      if lessons
        lessons.each do |lesson|
          @start_time = lesson.start_time
          @end_time = lesson.end_time
          @day_of_week = lesson.weekday
          @room = Room.find(lesson.room_id).name
          @lesson_length = (@end_time - @start_time)/60/15
          @slot_number = (@start_time - first_slot_time)/60/15
          lesson.status.nil? ? @status = "s" : @status = lesson.status
          lesson.student_id.nil? ? @student = "" : @student = "#{lesson.student.first.first}. #{lesson.student.last}"
        
          if lesson.status == "sh"
            @student = "SHARING"
          else
          lesson.teacher_id.nil? ? @teacher_name = "Need Sub" : @teacher_name = lesson.teacher.first
          end
      
      
          @columns[@day_of_week].push({ 
            :id => lesson.comp_id,
            :weekday => lesson.weekday,
            :room => @room, 
            :teacher => @teacher_name,
            :student => @student, 
            :start_time => @start_time, 
            :end_time => @end_time, 
            :slot => @slot_number,  
            :length => @lesson_length,
            :status => @status }) #  default is (s = scheduled)
        end
      end
    
  #  @slot contains an array of lessons for each slot.
    
      @slot = Array.new
      d = 0
      while d < num_columns do
        @slot[d] = Array.new(num_rows){Array.new}
        d += 1
      end
    
      if @columns
        @columns.each do |column|
          if column != nil
            i = 0
            while i < column.count do
              t = 0
              while t < column[i][:length] do
                @number = column[i][:slot] + t
                #@room = column[i][:room]
                @weekday = column[i][:weekday]
                @slot[@weekday][@number].push(column[i][:id])
                t += 1
              end
              i += 1
            end
          end
        end
      end
    
  #  @max_num is an array of max number of conflicts for each lesson for each room.

      @max_num = Array.new
      d = 0
      while d < num_columns do
        @max_num[d] = Hash.new
        d += 1
      end
    
      d = 0
      while d < num_columns do
        if @columns[d] != nil
          @columns[d].each do |column|
            i = 0
            while i < column[:length]
              @slot_number = column[:slot]
              @keys = @slot[d][@slot_number].count
              @keys_next = @slot[d][@slot_number + i].count
              @lesson_id = column[:id]
              @max_num[d].merge!({@lesson_id => @keys})
              if @keys_next > @max_num[d][@lesson_id]
                t = 0
                while t < column[:length]
                  @slot[d][@slot_number + t].each do |event|
                    @max_num[d][event] = @keys_next
                  end
                  t += 1
                end
              end
              i += 1
            end
          end

app/views/calendars/_header.html.erb
<header >
	<div class = "navbar-fixed-top">
		<div class = "header-top" >
			<% if user_signed_in? %>
				<div class = "pull-right sign-out">
					<%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>
				</div>
			<% end %>
			<div id="day">
					
					<%= link_to "<", daily_path(date: @previous, teacher_id: @teacher_id), method: "get", class: "link-button", id: "previous"  %>
				
					<%= link_to "Today", daily_path(teacher_id: @teacher_id), method: "get", class: "link-button", id: "today"%>
					
					<%= link_to ">", daily_path(date: @next, teacher_id: @teacher_id), method: "get", class: "link-button", id: "next"  %>
					
					<input  id = "date-select" class ="link-button" type="text" readonly="readonly">
					<p class="inline day">
						<%= @day %>
					</p>
			</div>
		</div>

		<div class="navbar">
			<div class="navbar-inner">
				<ul class="nav pull-right">
					<% if user_signed_in? %>
					<li class = "<%= current_page?(root_path) ? "active" : "" %> dropdown" >
						<%= link_to "Home", root_path %>
						<% @teacher = Teacher.find(current_user.loginable_id) %>
						<ul class="dropdown-menu" role="menu">
							<li>
								<%= link_to "Change your password", edit_user_registration_path %>
							</li>
							<li>
								<%= link_to 'Edit personal info', edit_teacher_path(@teacher) %>
							</li>
						</ul>
					</li>
					<li class = "<%= active_link("calendars") %> dropdown">
						<%= link_to "Calendar", daily_path %>
						<ul class="dropdown-menu" role="menu">
							<li>
								<%= link_to "Daily attendance", teacher_daily_path(@teacher) %>
							</li>
							<li>
								<%= link_to "Weekly schedule", teacher_weekly_path(@teacher) %>
							</li>
						</ul>
					</li>
					<li class = <%= active_link("customers") %> >
						<%= link_to "Customers", customers_path %>
					</li>
					<li class = <%= active_link("students") %> >
						<%= link_to "Students", students_path %>
					</li>
					<li class = <%= active_link("teachers") %> >
						<%= link_to "Teachers", teachers_path %>
					</li>
					<li class = "dropdown" >
						<%= link_to "Admin", root_path, disabled: true %>
						<ul class="dropdown-menu" role="menu">
							<li class = <%= active_link("sharings") %> >
						<%= link_to "Sharings", sharings_path %>
					</li>
							<li class = <%= active_link("instruments") %> >
						<%= link_to "Instruments", instruments_path %>
							</li>
							<li class = <%= active_link("rooms") %> >
								<%= link_to "Rooms", rooms_path %>
							</li>
						</ul>
					</li>
					<% end %>
				</ul>
			</div>
        </div>
		<div id="rooms">
			<table id="days">
				<tr>
					<td class="blank">&nbsp;</td>
						<% for room in @rooms do %>
					<td class="room-header"><%= room.name %></td>
						<% end %>
				</tr>
			</table>
		</div>
	</div>
	
</header>

app/views/calendars/_weekly_header.erb
<header >
	<div class = "navbar-fixed-top">
		<div class = "header-top" >
			<% if user_signed_in? %>
				<div class = "pull-right sign-out">
					<%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>
				</div>
			<% end %>
			<div id="day">
					<%= link_to "<", teacher_weekly_path(@teacher, date: @previous), method: "get", class: "link-button", id: "previous"  %>
					<%= link_to "This Week", teacher_weekly_path(@teacher), method: "get", class: "link-button", id: "today"%>
					<%= link_to ">", teacher_weekly_path(@teacher, date: @next), method: "get", class: "link-button", id: "next"  %>
					<input  id = "date-select" class ="link-button" type="text" readonly="readonly">
					<p class="inline day">
						<%= "Weekly schedule for #{@teacher.first}" %>
					</p>
			</div>
		</div>

		<div class="navbar">
			<div class="navbar-inner">
				<ul class="nav pull-right">
					<% if user_signed_in? %>
					<li class = "<%= current_page?(root_path) ? "active" : "" %> dropdown" >
						<%= link_to "Home", root_path %>
						<% @teacher = Teacher.find(current_user.loginable_id) %>
						<ul class="dropdown-menu" role="menu">
							<li>
								<%= link_to "Change your password", edit_user_registration_path %>
							</li>
							<li>
								<%= link_to 'Edit personal info', edit_teacher_path(@teacher) %>
							</li>
						</ul>
					</li>
					<li class = "<%= active_link("calendars") %> dropdown" >
						<%= link_to "Calendar", daily_path %>
						<ul class="dropdown-menu" role="menu">
							<li>
								<%= link_to "Daily attendance", teacher_daily_path(@teacher) %>
							</li>
							<li>
								<%= link_to "Weekly schedule", teacher_weekly_path(@teacher) %>
							</li>
						</ul>
					</li>
					<li class = <%= active_link("customers") %> >
						<%= link_to "Customers", customers_path %>
					</li>
					<li class = <%= active_link("students") %> >
						<%= link_to "Students", students_path %>
					</li>
					<li class = <%= active_link("teachers") %> >
						<%= link_to "Teachers", teachers_path %>
					</li>
					<li class = "dropdown" >
						<%= link_to "Admin", root_path, disabled: true %>
						<ul class="dropdown-menu" role="menu">
							<li class = <%= active_link("sharings") %> >
						<%= link_to "Sharings", sharings_path %>
					</li>
							<li class = <%= active_link("instruments") %> >
						<%= link_to "Instruments", instruments_path %>
							</li>
							<li class = <%= active_link("rooms") %> >
								<%= link_to "Rooms", rooms_path %>
							</li>
						</ul>
					</li>
					<% end %>
				</ul>
			</div>
        </div>
		<div id="rooms">
			<table id="days">
				<tr>
				<td class="blank">&nbsp;</td>

			<% d = 0 %>
			<% while d < 7 do %>
			<% @day = @date + d*24*60*60 %>
				<td class="day-header"><%= @day.strftime("%A") %><br><%= @day.strftime("%b #{@day.day.ordinalize}, %Y") %></td>
				<% d += 1 %>
			<% end %>
				</tr>
			</table>
		</div>
	</div>
</header>

app/views/calendars/daily.html.erb
<% provide(:title, 'Daily Calendar') %>
<% prerender_calendar(@lessons, @rooms, @num_rooms, @num_rows, @first_slot_time) %>
<%= render 'header' %>
<% @calendar_start_time = Time.new(2000, 1, 1, 6, 0, 0 ) %>
<% i = 6 %>
<div id="grid-hour">
	<table id="hour-column" >		
		
		<% while i < 20 do %>
			<% @hour = @calendar_start_time.strftime("%l : %M %p") %>
		
			<tr>
				<td class="time-header">
					<p class="time-display"><%= "#{@hour}"%></p>
				</td>
			</tr>
			<% @calendar_start_time += (60 * 60) %>
			<% i +=1 %>
			
		<% end %>
			
	</table>
</div>

<div id="test">
	<div id="day-container">

		<% d = 1 %>
		<% while d < @num_rooms+1 do %>
			<% @room = d %>

			<div class="grid-room" id="<%= '#{@room}' %>">
				<table class="day-column" >
					<% i = 0 %>
					<% while i < 14 do %>
						<% e = 0 %>
						<% while e < 4 do %>
							<% if e < 3 %>
								<tr><td class="time-slot"></td></tr>
							<% else %>	
								<tr><td class="time-slot-hour"></td></tr>
							<% end %>
							<% e += 1 %>
						<% end %>
						<% i += 1 %>
					<% end %>			
				</table>
				
				<% if @columns[d] != nil
					@columns[d].each do |column|
						@height = (column[:length]*25).to_i
						@width = (100/@max_num[d][column[:id]]*@num_slots[column[:id]]).to_i
						@x_ind = (100/@max_num[d][column[:id]]*@index_array[d][column[:id]]).to_i
						@top = (column[:slot]*25).to_i
						@lesson_id = column[:id] 
						@teacher = column[:teacher] 
						@student = column[:student]
						@status = column[:status]
						@color = event_color(column[:status])
						@h_color = @color - 50 %>
				
				<div id = "<%= "#{@lesson_id}" %>" class="event" style="position:absolute; top: <%= @top %>px; left: <%= @x_ind %>%; height: <%= @height %>px; width: <%= @width %>%; background-color: #<%= @color.to_s(16) %>; color:black;">
					<h4 class="event_heading" style = "background-color: #<%= @h_color.to_s(16) %>;"><%= @teacher %></h4>
					<p class="purpose"><%= @student %></p>
				</div>
					<% end %>
				<% end %>
			</div>
			
			<% d += 1 %>
		<% end %>
	</div>
</div>
<%# if (current_user.loginable_type == "Teacher" and params[:teacher_id]) or current_user.loginable_type == "Admin" %>
		<div id="attendance-dialog" style="display:none;"></div>
<%# end %>

app/views/calendars/weekly.html.erb
<% provide(:title, 'Weekly Calendar') %>
<% prerender_weekly_calendar(@lessons, @num_columns, @num_rows, @first_slot_time) %>
<%= render 'weekly_header' %>
<% @calendar_start_time = Time.new(2000, 1, 1, 6, 0, 0 ) %>
<% i = 6 %>
<div id="grid-hour">
	<table id="hour-column" >		
		
		<% while i < 20 do %>
			<% @hour = @calendar_start_time.strftime("%l : %M %p") %>
		
			<tr>
				<td class="time-header">
					<p class="time-display"><%= "#{@hour}"%></p>
				</td>
			</tr>
			<% @calendar_start_time += (60 * 60) %>
			<% i +=1 %>
			
		<% end %>
			
	</table>
</div>
<div id="test">
	<div id="day-container">

		<% d = 0 %>
		<% while d < 7 do %>
			<% @room = d %>

			<div class="grid-day" id="<%= '#{@room}' %>">
				<table class="day-column" >
					<% i = 0 %>
					<% while i < 14 do %>
						<% e = 0 %>
						<% while e < 4 do %>
							<% if e < 3 %>
								<tr><td class="time-slot"></td></tr>
							<% else %>	
								<tr><td class="time-slot-hour"></td></tr>
							<% end %>
							<% e += 1 %>
						<% end %>
						<% i += 1 %>
					<% end %>			
				</table>
				
				<% if @columns[d] != nil
					@columns[d].each do |column|
						@height = (column[:length]*25).to_i
						@width = (100/@max_num[d][column[:id]]*@num_slots[column[:id]]).to_i
						@x_ind = (100/@max_num[d][column[:id]]*@index_array[d][column[:id]]).to_i
						@top = (column[:slot]*25).to_i
						@lesson_id = column[:id] 
						@teacher = column[:teacher] 
						@student = column[:student]
						@room = column[:room]
						@status = column[:status]
						@color = event_color(column[:status])
						@h_color = @color - 50
						@description = lesson_category_decoder(@lesson_id) %>
				
				<div id = "<%= "#{@lesson_id}" %>" class="event" style="position:absolute; top: <%= @top %>px; left: <%= @x_ind %>%; height: <%= @height %>px; width: <%= @width %>%; background-color: #<%= @color.to_s(16) %>; color:black;">
					<h4 class="event_heading" style = "background-color: #<%= @h_color.to_s(16) %>;"><%= @student %></h4>
					<p class="purpose"><%= @description %></p>
				</div>
					<% end %>
				<% end %>
			</div>
			<% d += 1 %>
		<% end %>		
	</div>
</div>