config/routes.rb
Studio::Application.routes.draw do

  mount_opro_oauth
  devise_for :users, :controllers => {:sessions => "sessions"} 
  devise_scope :user do

    authenticated :user, lambda { |user| user.loginable_type == "Admin" } do
      root to: "customers#index"
    end

    authenticated :user, lambda { |user| user.loginable_type == "Teacher" } do
      root to: "teachers#personal", as: :teacher_root
    end

    unauthenticated :user do
      root :to => 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources   :users

  get '/daily', to: 'calendars#daily'
  
  get 'update_teachers', to: 'shared#update_teachers'
  
  get "lessons/teacher_booking"
  
  resources :lessons do
    get "sub_request", to: "attendances#sub_request"
    resources :attendances
  end
  
  get "extras/teacher_booking"
  
  resources :extras do
    resources :attendances
  end
  
  get "attendances/dialog"

  resources :instruments

  resources :rooms

  resources :teachers do
    devise_for :users, :controllers => {:registrations => "registrations"} 
    get 'weekly', to: 'calendars#weekly'
    get '/daily', to: 'calendars#daily'
  end
  
  get 'teachers_cbx', to: 'sharings#teachers_cbx'
  
  get 'teacher', to: 'teachers#personal'
  
  get 'sharing_search', to: 'detailed_sharings#sharing_search'
  
  match "update_attendance", to: "detailed_sharings#update_attendance", :via => :put
  
  resources :sharings do
    get "attendance", to: "detailed_sharings#attendance"
  end

  get 'attendance_search', to: 'students#attendance_search'
  
  resources :students do
    get 'attendance', to: 'students#attendance'
    resources :lessons
    resources :extras
    resources :detailed_sharings
  end
  
  get "customers/live_search"
  
  resources :customers do
    resources :students
    resources :telephones
    resources :addresses do
      resources :preffered_addresses
    end
    
  
  end

end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id         :integer          not null, primary key
#  first      :string(255)
#  last       :string(255)
#  email      :string(255)
#  status     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Teacher < ActiveRecord::Base
  include FieldSanitizer
  
	has_many :telephones, :as => :phoneable, :dependent => :destroy
	accepts_nested_attributes_for :telephones, :allow_destroy => true, :reject_if => proc { |attributes| attributes['number'].blank? }
  
  has_many :addresses, :as => :addressable
  accepts_nested_attributes_for :addresses
  
  has_and_belongs_to_many :instruments
  
  has_many :lessons
  has_many :extras

  has_one :user, as: :loginable
  accepts_nested_attributes_for :user
  
  attr_accessible :address_id, :email, :status, :first, :last, :telephones_attributes, :addresses_attributes, :instrument_ids, :users_attributes
  
  before_validation { |teacher| teacher.nameize :first, :last }
  before_validation { |teacher| teacher.email = teacher.email.strip.downcase }
  
  validates_associated :telephones, presence: { message: "Please enter a valid number." }
  validates_presence_of :telephones, message: "Enter a valid number"
  
	validates :first, presence: {message: "Enter first name"}, length: { maximum: 30 } 
	validates :last, presence: {message: "Enter last name"}, length: { maximum: 30 }
	validates :email, presence: {message: "Enter a valid email"}, length: { maximum: 80 }
	validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, message: "Enter a valid email" }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :check_for_mobile, :only => [:personal, :edit, :show]
  allow_oauth!
  def index
    @teachers = Teacher.all
  end

  def show
    if current_user
      @user = current_user
      if @user.loginable_type == "Teacher"
        @teacher = Teacher.find(@user.loginable_id)
        @mailing = @teacher.addresses.first
      end
    end
    #@teacher = Teacher.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @teacher }
    end
  end

  def new
    @teacher = Teacher.new
    @teacher.telephones.build
    @teacher.addresses.build
    @selected = 'AZ'
    @address_description = 'mailing'
  end

  def edit
    @teacher = Teacher.find(params[:id])
    @selected = @teacher.addresses.first.state
    @address_description = 'mailing'
    if @teacher.telephones.empty? 
      @teacher.telephones.build
    end
  end

  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
      else
        @selected = params[:teacher][:addresses_attributes].values.first[:state]
        format.html { render action: "new" }
        if @teacher.telephones.empty? 
          @teacher.telephones.build
        end
        @address_description = 'mailing'
      end
    end
  end

  def update
    params[:teacher][:instrument_ids] ||= []
    @teacher = Teacher.find(params[:id])
    @selected = @teacher.addresses.first.state
    @address_description = 'mailing'

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html #{ redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        if @teacher.telephones.empty?
          @teacher.telephones.build
        end
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.js
    end
  end

  def personal
    if current_user
      @user = current_user
      if @user.loginable_type == "Teacher"
        @teacher = Teacher.find(@user.loginable_id)
        @mailing = @teacher.addresses.first
        @teacher_cell = @teacher.telephones.where("description = 'Cell'").first
        @teacher_instruments = @teacher.instruments
        @instrument_ids = Array.new
        @teacher_instruments.each do |instrument|
          @instrument_ids.push(instrument.id)
        end
        @json_teacher = @teacher.attributes
        @json_teacher["cell"] = @teacher_cell.number
        @json_teacher["instrument_ids"] = @instrument_ids
        respond_to do |format|
          format.html
          format.json { render :json => @json_teacher }
        end
      end
    end
  end
  
end

app/views/teachers/_form.html.erb
<div class="form-container">
<%= form_for(@teacher, :html => {'data-ajax' => 'false'}) do |f| %>
  
  <fieldset><legend>Contact Info</legend>
	<%= render "layouts/basic_info_form", :f => f, :@person => @teacher %>
	<div class="field">
	<%= f.label :status, "Status" %>
	<%= f.select(:status, options_for_select([['Regular','r'],['Substitute', 's'],['Inactive', 'i']]), {:include_blank => false }, {class: "input-med", 'data-role' =>'none'}) %>
  </div></br>
	  
  	<%= f.fields_for :telephones do |builder| %>
	<% @collection = phone_collection "B" %>
	<!-- view telephones_helper for available collections -->
    	<%= render "telephones/telephone_fields", :f => builder, :@person => @teacher %>
  	<% end %>
  <div class="field">
   <% mobile_device? ? @title = "" : @title = "Add phone number" %>
   <%= link_to_add_fields '<i class="icon-plus icon-white"></i>'.html_safe, f, :telephones, {class: "btn btn-success", title: @title} %>
  </div>
</fieldset>
  <div>
	<%= f.fields_for :addresses do |builder| %>
  		<%= render "addresses/addresses_fields", :f => builder, :@person => @teacher %>
	<% end %>
  </div>
  
  <% for instrument in Instrument.all %>  
      <div class="field"> 
      <label> 
        <%= check_box_tag "teacher[instrument_ids][]", instrument.id, @teacher.instruments.include?(instrument), :class => 'checkbox', 'data-role' =>'none' %>  
      <%= instrument.name %>
      </label> 
      </div>  
  <% end %>
  
  <div class="actions">
    <%= f.submit submit_button_message(yield(:button_message)), class: "btn btn-large btn-primary", 'data-role' =>'none' %>
  </div>
<% end %>
</div>

app/views/teachers/edit.html.erb
<% provide(:title, 'Update Teacher') %>
<% provide(:button_message, 'Update Teacher') %>

<% unless mobile_device? %>
	<h1>Editing teacher</h1>
<% else %>
	<%= link_to "Home", root_path, class: "ui-btn ui-corner-all ui-btn-icon-left ui-icon-home", "data-ajax" => "false"%>
<% end %>

<%= render 'form' %>

<% unless mobile_device? %>
	<%= link_to 'Show', @teacher %> |
	<%= link_to 'Back', teachers_path %>
<% end %>

app/views/teachers/index.html.erb
<% provide(:title, 'Teachers') %>
<table class="table table-hover">
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
	<th></th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.first %></td>
    <td><%= teacher.last %></td>
    <td><%= teacher.email %></td>
    <td><%= link_to 'Info', teacher %></td>
    <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
	<td><%= link_to image_tag("calendar.jpg",title: "weekly calendar", class: "calendar-icon tooltip_right"), teacher_weekly_path(teacher) %></td>
    <td><%= link_to '<i class="icon-minus icon-white"></i>'.html_safe, teacher, method: :delete, remote: true, title: "Delete teacher", class: "triger btn btn-mini btn-danger bold tooltip_right" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teacher', new_teacher_path, class: "btn btn-small btn-primary" %>
<%= render :partial => 'shared/alert' %>

app/views/teachers/new.html.erb
<% provide(:title, 'New Teacher') %>
<% provide(:button_message, 'Add Teacher') %>

<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/personal.html.erb
<h1>Personal info</h1>
<p><%= "Welcome #{@teacher.first}" %></p>
<%= link_to "Change your password", edit_user_registration_path %> |
<%= link_to "Weekly schedule", teacher_weekly_path(@teacher) %> |
<%= link_to "Daily attendance", teacher_daily_path(@teacher) %> |
<%= link_to 'Edit personal info', edit_teacher_path(@teacher) %>

app/views/teachers/show.html.erb
<p>
	<b>Teacher:</b>
	<%= "#{@teacher.first} #{@teacher.last}" %> 
</p>
<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>
<p>
  <b>Telephones:</b>
</p>
<ul>
	<% if @teacher.telephones.any? 
		for telephone in @teacher.telephones %>
			<li>
				<%= formated_phone(telephone.number) %>&nbsp;
				<%= telephone.description %>
			</li>
		<% end %>
	<% end %>
</ul>
<p>
    <b>Address:</b></br>
    <%= "#{@mailing.street}" %></br> 
	<%= "#{@mailing.city}, #{@mailing.state} #{@mailing.zip}" %>	
</p>
<p>
    <b>Instruments:</b></br>
	<ul>
	<% for instrument in @teacher.instruments %>
    <li><%= "#{instrument.name}" %></li>
	<% end %>
</ul>
</p>



<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>